# Generated by Django 5.0.6 on 2024-11-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Цифра')),
                ('letter', models.CharField(blank=True, max_length=1, null=True, verbose_name='Буква')),
                ('is_graduated', models.BooleanField(default=False, verbose_name='Выпустился')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
            ],
        ),
    ]
